### ISSUE TITLE
SVM训练的问题

### ISSUE THREAD

**Issue by joewale** [Micooz/EasyPR#2]
@micooz 我运行命令：./demo svm --plates=resources/image/plates --svm=resources/model/svm.xml
出现以下的结果，很明显训练出来的模型好像不对，进行测试发现，确实不能用。请问这是哪里出错导致的？

![easyprerror](https://cloud.githubusercontent.com/assets/9114449/10933693/63197f84-8315-11e5-838f-918a7dec6f5d.png)

**Comment by micooz** [comment]
这个问题已经解决了，请查看 v1.3 或 v1.4
